name: df_logger
description: Logcat-like Flutter console logger.
version: 2.0.1
homepage: https://github.com/ojciec-dev/df_logger

publish_to: 'https://pub.scrobosoft.space'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
